name: CI
on:
  push:
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Check markdown-lint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: "**/*.md"
      - name: Check prettier
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: . --check
